PROJECTNAME=Zfmsdk
WIN32DIR=bin\Win32\Release
WIN64DIR=bin\Win64\Release
DLL32=$(WIN32DIR)\Zfm.dll
DLL64=$(WIN64DIR)\Zfm.dll
MSBUILD=C:\Windows\Microsoft.NET\Framework\v3.5\MSBUILD.exe
SIGNTOOL="C:\Program Files (x86)\Windows Kits\8.1\bin\x86\signtool.exe"
CERTSHA1=A9A273A222A5DD3ED9EC2F46232AAD8E087EA4ED
SIGN=$(SIGNTOOL) sign /v /sha1 $(CERTSHA1) /tr http://timestamp.globalsign.com/scripts/timstamp.dll /td SHA256 /fd SHA256
ZIP="C:\Program Files (x86)\GnuWin32\bin\zip.exe"

build: win32 win64

win32: $(PROJECTNAME).groupproj
	SET BDS=C:\Program Files (x86)\Embarcadero\Studio\16.0
	IF NOT EXIST bin\Win32 MKDIR bin\Win32
	$(MSBUILD) /p:Config=Release /property:Platform=Win32 "$(PROJECTNAME).groupproj"

win64: $(PROJECTNAME).groupproj
	SET BDS=C:\Program Files (x86)\Embarcadero\Studio\16.0
	IF NOT EXIST bin\Win64 MKDIR bin\Win64
	$(MSBUILD) /p:Config=Release /property:Platform=Win64 "$(PROJECTNAME).groupproj"

sign: $(DLL32) $(DLL64)
	$(SIGN) $(DLL32) $(DLL64)

source: src\*.pas Makefile
	$(ZIP) -9 -r $(PROJECTNAME)-src.zip . src sample gui doc -x .hg\* -x BACKUP\* -i MakeFile -i MakeFile.bat -i *.pdf -i *.txt -i *.pas -i *.h -i *.cs -i *.dproj -i *.groupproj -i *.res -i *.rc -i *.dpr -i *.lps -i *.lpi -i *.dfm -i *.inc -i *.dcr -i *.ico

pack:
	$(ZIP) -9 -r $(PROJECTNAME).zip bin -i *.dll -i *.exe

release: build sign pack source

clean:
	IF EXIST $(DLL32) DEL $(DLL32)
	IF EXIST $(DLL64) DEL $(DLL64)
